### ISSUE TITLE
[1.15pre] fisticuffs with libcd

### ISSUE THREAD

**Issue by Yoghurt4C** [Siphalor/nbt-crafting#26]
doing a `/reload` breaks all of libcd's pseudotag ingredients when nbtcrafting is present.

reproduction:
-get libcd and nbtcrafting
-get a datapack and make a `data/namespace/tweakers/whatever.js` file
-inside the file, place the following:
```javascript
var sample1=RecipeTweaker.makeIngredient("fuzzy","minecraft:diamond","minecraft:bedrock");
RecipeTweaker.addShaped([
	[sample1]],
	TweakerUtils.createItemStack("minecraft:dirt",1));
```
-save and runClient
-observe as the recipe works
-do `/reload`
-observe

**Comment by Nathan22211** [comment]
from me having both mods installed and using them for my datapacks. my loot script hasn't broken with NBT crafting installed.

**Comment by Siphalor** [comment]
@Yoghurt4C 
Can you please verify that this bug still exists?
Otherwise I'm gonna consider this bug as gone 🙂

**Comment by DuncanRuns** [comment]
The bug report should probably include the imports for reproduction as they are needed for the libcd recipe to work in the first place:
`var RecipeTweaker = libcd.require("libcd.recipe.RecipeTweaker");
var TweakerUtils = libcd.require("libcd.util.TweakerUtils");;`

Anyway, with nbt crafting 2.0 alpha 10 and libcd 2.2.2 on version 1.15.2, the libcd recipe works before and after a reload, so this bug is fixed.

**Comment by Siphalor** [comment]
Nice thanks 😁
