### ISSUE TITLE
[bug] example title

### ISSUE THREAD

**Issue by Nathan22211** [Siphalor/nbt-crafting#36]
**Version**
Minecraft version: 1.15.1
NBT crafting version: 1.2.12
**Describe the bug**
recipes with enchantment books that try to craft enchantments in an anvil higher than they go in vanilla e.g. multishot 1 to multishot 2, causes the enchantment to be removed entirely.

**To Reproduce**
1. Use the recipes crossshot2-4 in this datapack https://www.curseforge.com/minecraft/customization/enchant-rework
2. the crossbow should now have no multishot (and for some reason no name)

**Expected behavior**
The crossbow should have multishot 2-5 depending on which one you test.

**Log**
This is an issue when the recipe's output and I'm pretty sure recipes being used aren't logged

**Additional context**

**Comment by Siphalor** [comment]
Your recipe json file is flawed: 🙂 
The property where you write the enchantments is called `Enchantments` instead of `StoredEnchantments`. If you change that it will apply the enchantment.
Please note that due to #14 the old enchantment will be kept. This will most notably look ugly but would require a method to remove a specific list element which is not possible yet.

Also you might want to point out in the CurseForge description which mods you used as of my experience most people don't look at the "Relations" tab and just complain that it doesn't work 😉
